language: python
python:
  - "2.7"
install:
  - "pip install -r requirements.txt"
  - "pip install coveralls"
script:
  - coverage run -p --source=src manage.py test
  - coverage run -p --source=src manage.py integration-test
  - coverage combine
after_success:
  coveralls